server {
    # Escuta na porta 3838 (a mesma que o Shiny usava e que o roteador já conhece)
    listen 3838;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        # Essencial para o React Router funcionar (não dar erro 404 ao atualizar a página)
        try_files $uri $uri/ /index.html;
    }
}
